对前言与1~2章的小修改
CTeX-org/tex-by-topic-cn pull request #1
Opened 2018-05-09 11:26 UTC by inkydragon

有不合适的地方务必请指出，下次我就直接push了。

一开始还想纠结一下某些地方的格式统一、语句的直译/改写问题。后来一想填完坑了再改也不迟。
毕竟之前开的坑都净关注细节去了。<-翻译没做多少，天天折腾模板，还学了一手repo的瘦身技术。

2018-05-09 11:59 UTC, Stone-Zeng commented on chapter02.tex
> +输入行的具体定义有所不同。最常见的方式是用回车符（carr\-iage return）紧跟换行符（line feed）作为行尾符，有些系统单用换行符作为行尾符，一些有定长存储（块存储）的系统则根本不使用行尾符。因此，\TeX 在结束一行输入时有自己特定的处理方式。
carriage 的断词应该是 car-riage。见 <https://www.merriam-webster.com/dictionary/carriage>

2018-05-09 14:37 UTC, Liam0205 requested changes
见 line note。

2018-05-09 14:37 UTC, Liam0205 commented on chapter02.tex
> +输入行的具体定义有所不同。最常见的方式是用回车符（carr\-iage return）紧跟换行符（line feed）作为行尾符，有些系统单用换行符作为行尾符，一些有定长存储（块存储）的系统则根本不使用行尾符。因此，\TeX 在结束一行输入时有自己特定的处理方式。
赞成 @Stone-Zeng ，这里确实断词不对。之前是我弄错了。

2018-05-10 12:24 UTC, inkydragon commented
@Liam0205 已修复√

2018-05-10 14:16 UTC, merged